# Generated by Django 4.1.2 on 2022-11-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
