# Generated by Django 4.1.2 on 2022-11-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_employee_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
