# Generated by Django 4.1.2 on 2022-11-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_employee_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updateedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
