# Generated by Django 4.1.2 on 2022-11-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_employee_birthdate_employee_birthtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('fees', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('coursemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.coursemodel')),
                ('sname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('pasword', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'student',
            },
            bases=('blog.coursemodel',),
        ),
    ]
