# Generated by Django 4.1.2 on 2022-11-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hobbies', models.CharField(choices=[('sports', 'Sports'), ('music', 'Music'), ('reading', 'Reading'), ('movies', 'Movies'), ('travel', 'Travel'), ('cooking', 'Cooking')], max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'user1',
            },
        ),
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('user', models.ManyToManyField(to='media.user')),
            ],
            options={
                'db_table': 'netflix',
            },
        ),
    ]
